create table sellers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique
);

create table buyers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique
);

create table products (
    id bigint generated by default as identity primary key,
    seller_id bigint not null,
    title varchar(255) not null,
    category varchar(255) not null,
    price numeric(12, 2) not null,
    constraint fk_products_seller foreign key (seller_id) references sellers (id)
);

create table seller_orders (
    id bigint generated by default as identity primary key,
    seller_id bigint not null,
    buyer_id bigint not null,
    status varchar(255) not null,
    placed_at timestamp not null,
    constraint fk_orders_seller foreign key (seller_id) references sellers (id),
    constraint fk_orders_buyer foreign key (buyer_id) references buyers (id)
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_title varchar(255) not null,
    unit_price numeric(12, 2) not null,
    quantity integer not null,
    constraint fk_order_items_order foreign key (order_id) references seller_orders (id),
    constraint fk_order_items_product foreign key (product_id) references products (id)
);

create table questions (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    buyer_id bigint not null,
    product_id bigint,
    message varchar(1000) not null,
    answer varchar(1000),
    status varchar(255) not null,
    priority varchar(255) not null,
    priority_score integer not null,
    created_at timestamp not null,
    answered_at timestamp,
    resolved_at timestamp,
    constraint fk_questions_order foreign key (order_id) references seller_orders (id),
    constraint fk_questions_buyer foreign key (buyer_id) references buyers (id),
    constraint fk_questions_product foreign key (product_id) references products (id)
);

create table notifications (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    channel_type varchar(255) not null,
    recipient varchar(255) not null,
    message varchar(1000) not null,
    created_at timestamp not null,
    constraint fk_notifications_question foreign key (question_id) references questions (id)
);

create index idx_products_seller_id on products (seller_id);
create index idx_orders_seller_id on seller_orders (seller_id);
create index idx_orders_buyer_id on seller_orders (buyer_id);
create index idx_order_items_order_id on order_items (order_id);
create index idx_questions_order_id on questions (order_id);
create index idx_questions_status on questions (status);
create index idx_notifications_question_id on notifications (question_id);
