create table outbox_events (
    id bigint generated by default as identity primary key,
    event_id uuid not null unique,
    idempotency_key varchar(255) not null unique,
    event_type varchar(100) not null,
    aggregate_type varchar(100) not null,
    aggregate_id bigint not null,
    payload text not null,
    status varchar(30) not null,
    attempt_count integer not null default 0,
    available_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    last_error varchar(1000)
);

create table outbox_deliveries (
    id bigint generated by default as identity primary key,
    event_id uuid not null unique,
    delivered_at timestamp not null,
    constraint fk_outbox_deliveries_event foreign key (event_id) references outbox_events (event_id)
);

create index idx_outbox_events_due on outbox_events (status, available_at, id);
